### ISSUE TITLE
npm-consider fails on "Impact" 

### ISSUE THREAD

**Issue by Themayu** [delfrrr/npm-consider#11]
The issue is exactly as the title says: `npm-consider` seems to fail when selecting `Impact`. Associated command output with stack trace is below (tested using `express` with command `npm-consider install --save express`):

```
***@***:~/proj/zifar$ npm-consider install --save express
express@4.16.3 (updated 6 months ago)
Packages  51
Size      535.18 KB
Licenses  Permissive  51
? What is next? Impact
TypeError: Cannot read property 'saveDev' of undefined
    at getLocalPackage.then (/mnt/c/Users/***/AppData/Roaming/npm/node_modules/npm-consider/lib/showImpact.js:69:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Note that this error also occurs if I attempt to use the module directly in the Windows command prompt.

Additionally, selecting

**Comment by Themayu** [comment]
Edit: accidentally hit CTRL+ENTER while sending, then realised what I was typing didn't even matter anyway so I removed it.

**Comment by fgeorges** [comment]
Just got the same error, it seems, on macOS.  The following is what I tried exactly:

    $ npm install -g npm-consider
    /Users/xxx/.nvm/versions/node/v13.1.0/bin/npm-consider -> /Users/xxx/.nvm/versions/node/v13.1.0/lib/node_modules/npm-consider/bin/npm-consider.js
    + npm-consider@1.7.0
    added 59 packages from 45 contributors in 4.783s

    $ npm-consider install --save handlebars
    handlebars@4.5.2 (updated 4 days ago)
    Packages  8             
    Size      1.01 MB       
    Licenses  Permissive  8 
    ? What is next? Impact
    TypeError: Cannot read property 'saveDev' of undefined
        at /Users/xxx/.nvm/versions/node/v13.1.0/lib/node_modules/npm-consider/lib/showImpact.js:69:25
        at processTicksAndRejections (internal/process/task_queues.js:93:5)

As this been fixed somehow?

Or maybe someone has any clue on the problem, so I could try and help myself?
