### ISSUE TITLE
Check fails with FontAwesome

### ISSUE THREAD

**Issue by MarMun** [delfrrr/npm-consider#19]
**command I run:**
npm-consider install

**Packages I use:**
    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/pro-light-svg-icons": "^5.11.2",
    "@fortawesome/vue-fontawesome": "^0.1.8",

**Error I get:**
Error: Response is not ok  401 Unauthorized https://npm.fontawesome.com/@fortawesome%2ffontawesome-svg-core
    at checkResponse (/usr/local/lib/node_modules/npm-consider/lib/getPackageDetails.js:26:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by F3WS** [comment]
Same, still an issue...

Error: Response is not ok  401 Unauthorized https://npm.fontawesome.com/@fortawesome%2fpro-light-svg-icons
    at checkResponse (/usr/local/lib/node_modules/npm-consider/lib/getPackageDetails.js:26:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: Response is not ok  401 Unauthorized https://npm.fontawesome.com/@fortawesome%2ffontawesome-svg-core
    at checkResponse (/usr/local/lib/node_modules/npm-consider/lib/getPackageDetails.js:26:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: Response is not ok  401 Unauthorized https://npm.fontawesome.com/@fortawesome%2fpro-solid-svg-icons
    at checkResponse (/usr/local/lib/node_modules/npm-consider/lib/getPackageDetails.js:26:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: Response is not ok  401 Unauthorized https://npm.fontawesome.com/@fortawesome%2freact-fontawesome
    at checkResponse (/usr/local/lib/node_modules/npm-consider/lib/getPackageDetails.js:26:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by brettz9** [comment]
I'm not the maintainer, but it seems, as you can see in visiting the URLs in question, that you are using a registry which requires authentication. If you use the default of https://registry.npmjs.org for the registry, you might not have the problem.

**Comment by MarMun** [comment]
> using a registry which requires authentication.

Thats actually the case. I suggest to ignore registry in such a case (and warn about this in report)

**Comment by MarMun** [comment]
Sorry. Closed in error
