### ISSUE TITLE
Work with private packages (skip|ignore or do not throw an exception and stop the process)

### ISSUE THREAD

**Issue by vitivan** [delfrrr/npm-consider#28]
There is no chance to use npm-consider with private repositories.
It would be nice to have any of options:
- do not throw an exception (and stop the process) when try to get details for private package;
- config/flag option for package skip/ignore;

**Comment by ripso** [comment]
`Error: Response is not ok  401 Unauthorized https://npm.pkg.github.com/@XXXX%2fXXXX
    at checkResponse (/usr/lib/node_modules/npm-consider/lib/getPackageDetails.js:26:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
`

Same problem here.
It seems to fetch the private registry without considering the Personal Access Token.
