### ISSUE TITLE
Response is not ok when installing a package

### ISSUE THREAD

**Issue by delfrrr** [delfrrr/npm-consider#3]
```
 $ npx npm-consider i webvtt-parser
GET https://registry.npmjs.org/webvtt-parserError: Response is not ok
    at checkResponse (/Users/bilonenk/dev/lazy-german-subtitles/node_modules/npm-consider/lib/getPackageDetails.js:24:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by delfrrr** [comment]
Maybe something wrong with the package
```
$ npm i webvtt-parser
npm ERR! code E404
npm ERR! 404 Not Found: webvtt-parser@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bilonenk/.npm/_logs/2018-05-03T08_25_05_852Z-debug.log

```

**Comment by delfrrr** [comment]
#7 will also fix this
