### ISSUE TITLE
It does not work reason: connect ECONNREFUSED 104.18.97.96:443 !!!

### ISSUE THREAD

**Issue by denis99999** [delfrrr/npm-consider#5]
Hi,

My machine is behind a proxy, I set the npm proxy settings and 'npm install' works fine !
But when I try 'npm-consider install', it fails with this error:
```
GET https://registry.npmjs.org/http-proxy{ FetchError: request to https://registry.npmjs.org/@slack%2fclient failed, reason: connect ECONNREFUSED 104.18.95.96:443
    at ClientRequest.<anonymous> (/usr/lib/node_modules/npm-consider/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'FetchError',
  message: 'request to https://registry.npmjs.org/@slack%2fclient failed, reason: connect ECONNREFUSED 104.18.95.96:443',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
```
It seems `104.18.95.96:443` is hard-coded as a proxy by the tool because it is not the proxy I configured !

Thanks.

**Comment by denis99999** [comment]
But if the machine is not behind a proxy, it works well !

**Comment by delfrrr** [comment]
true, proxy is not supported.

**Comment by delfrrr** [comment]
Hi! I checked the address you mention `104.18.95.96`

```
$ traceroute 104.18.95.96
traceroute to 104.18.95.96 (104.18.95.96), 64 hops max, 52 byte packets
...
 7  cloudflare-ic-323372-bei-b1.c.telia.net (62.115.12.127)  4.000 ms  7.393 ms  3.886 ms
 8  104.18.95.96 (104.18.95.96)  5.190 ms  11.010 ms  7.913 ms
```
looks like the issue is with a network setup in your place; probably it will work if proxy support added to the tool (it will not go through this host but through the proxy);

if you can contribute and test proxy support, please do!
